
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Psychology'
tagline:          'from http://cnx.org/contents/4abf04bf-93a0-45c3-9cbc-2cefd46e68cc@7.2 (CC-BY)'
url:              https://github.com/philschatz/psychology-book
origin:           http://cnx.org/contents/4abf04bf-93a0-45c3-9cbc-2cefd46e68cc@7.2

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          7.2

bookviewer:       http://philschatz.com/book-viewer

